import '../../styles/globalStyles'
import Head from "next/head"
import styled, {ThemeProvider} from "styled-components"
import GlobalStyle from "../../styles/globalStyles";
import tempTheme from "../../styles/Themes/theme";
import Nav from "../components/Layout/Nav";
import Header from "../components/Layout/Header";
import React from "react";
import Footer from "../components/Layout/Footer";
import {isLocalURL} from "next/dist/shared/lib/router/router";

function MyApp({ Component, pageProps }) {

    return (
          <ThemeProvider theme={tempTheme}>
              <Head>
                  <title>Create Next App</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/img/favicon.png" />
                  {/*/!*bootStrep *!/*/}
                  {/*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"*/}
                  {/*      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"*/}
                  {/*      crossOrigin="anonymous" />*/}
                  {/*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"*/}
                  {/*        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"*/}
                  {/*        crossOrigin="anonymous"></script>*/}

                  <link rel="preconnect" href="https://cdn.tailwindcss.com"/>
                  <link href="https://cdn.tailwindcss.com"></link>
                  <link rel="preconnect" href="https://fonts.googleapis.com"/>
                  <link rel="preconnect" href="https://fonts.gstatic.com"/>
                  <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap" rel="stylesheet"/>
                  <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&family=Nanum+Gothic&display=swap" rel="stylesheet" />
              </Head>

              <Header />
            <GlobalStyle/>

            <ComponentContainer className = {"px-10 py-20"}>
                <Component {...pageProps} />
            </ComponentContainer>
              <Footer/>
          </ThemeProvider>
  )
}

const ComponentContainer = styled.div`
    background: ${(props) => props.theme.layoutColors.main};

`
export default MyApp
